[package]
name = "lychee-launcher"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
license = "GPL-3"

[dependencies]
fruit = { path = "fruit" }
pit = { path = "pit" }
slint = "1.12.1"
anyhow = "1.0.99"

[build-dependencies]
slint-build = "1.12.1"

[workspace]
resolver = "3"
members = ["fruit", "pit"]

[workspace.package]
edition = "2024"
repository = "https://github.com/LycheeLauncher/LycheeLauncher"
