[package]
name = "lychee-launcher"
version = "0.1.0"
edition.workspace = true
license = "Apache-2.0"

[dependencies]
http.workspace = true
piston.workspace = true

gpui = { git = "https://github.com/zed-industries/zed" }
serde_json.workspace = true
anyhow.workspace = true
bytes.workspace = true
