import { Button, VerticalBox, Spinner } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Lychee Launcher";

    default-font-size: 20px;

    callback gerald();

    VerticalBox {
        Text {
            text: "hello world";
            color: cyan;
        }

        Button {
            text: "gerald";
            clicked => {
                root.gerald();
            }
        }
    }
}
