[package]
name = "http"
version = "0.1.0"
edition.workspace = true
license = "MIT"

[dependencies]
reqwest = { version = "0.12.23", features = ["stream"] }
bytes.workspace = true
sha1_smol = { version = "1.0.1", features = ["std"] }
thiserror = "2.0.16"
futures-util = "0.3.31"
